---
 
    - hosts: 13.39.51.220
      gather_facts: no
      user: ubuntu
      connection: "ssh"
      become: true

    - name: Install and configure Docker
      hosts: all
      become: true
      tasks:
        - name: Update apt package lists
          apt:
            update_cache: true

        - name: Install dependencies
          apt:
            name: "{{ packages }}"
            state: present
          vars:
            packages:
              - apt-transport-https
              - ca-certificates
              - curl
              - software-properties-common

        - name: Add Docker's official GPG key
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

        - name: Add Docker's apt repository
          apt_repository:
            repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
            state: present

        - name: Install Docker CE
          apt:
            name: docker-ce
            state: present

        - name: Install Python3.9
          apt:
            name: python3.9
            state: present


        - name: Install containerd.io and the Docker Compose plugin
          apt:
            name: "{{ packages }}"
            state: present
          vars:
            packages:
              - containerd.io
              - docker-compose-plugin

        - name: Add user to the docker group
          user:
            name: ubuntu
            group: docker
            state: present
            
        - name: Copy necessary files
          copy:
            src: "{{ item }}"
            dest: /path/to/destination
            mode: 0644
          with_items:
            - Dockerfile
            - docker-compose.yml
            - requirements.txt
            - entrypoint.sh
            - app/

        - name: Start the Docker Compose service
          shell: docker-compose up
